name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 */3 * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Build
        run: |
          ./build.sh
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout --orphan build
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          mv dist/* ./ && git rm -rf .
          git add cidr.txt Country.mmdb
          git commit --no-gpg-sign -m "$(date +'%Y-%m-%d %H:%M:%S')"
          git push -f -u origin build
